/******************************
  
# 脚本功能：bkh056——去广告—会员解锁—m3u8捕获
# 目标站点：https://h5.bkh056.com
# 抓包校验：2026-06-07-204838 / 2026-06-07-220846
# 脚本作者：彭于晏💞
# 更新时间：2026-6-7
# 使用声明：此脚本仅供学习与交流，请勿转载与贩卖！⚠️⚠️⚠️

*******************************


[rewrite_local]

^https?:\/\/[^\/]+\/.*\.m3u8(\?.*)?$ url script-request-header https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/bkmh.js

^https?:\/\/[^\/]+\/.*\.flv(\?.*)?$ url script-request-header https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/bkmh.js

^https?:\/\/[^\/]+\/bkapi\/ url script-response-body https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/bkmhad.js

[filter-local]

^https?:\/\/52\.221\.252\.171\/ - reject

^https?:\/\/[^\/]+\/api\/eventTracking\/ - reject

[mitm]

hostname = h5.bkh056.com, *.bkh056.com, ghtawi.timemate.top, *.timemate.top, cdn.ugcpfgmf.com, *.ugcpfgmf.com, zqxz.bkk066.com, *.bkk066.com, luke-z.uciaxtue.com, *.uciaxtue.com, guxp-u.yrlrhbjr.com, *.yrlrhbjr.com, mzsb-m.swlxicnj.com, *.swlxicnj.com


*******************************/
