/******************************
  
# 脚本功能：JHA126(h9mcq系butterflyfly)——去广告—会员解锁—m3u8捕获
# 目标站点：https://d2x3hbu36ykmr8.cloudfront.net
# 抓包校验：2026-06-10-190711
# 脚本作者：彭于晏💞
# 更新时间：2026-6-10
# 使用声明：此脚本仅供学习与交流，请勿转载与贩卖！⚠️⚠️⚠️

*******************************


[rewrite_local]

^https?:\/\/[^\/]+\/api\/app\/media\/h5\/m3u8\/.+\.m3u8 url script-request-header https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/blsp.js

^https?:\/\/[^\/]+\/api\/app\/ url script-response-body https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/blspad.js

[filter-local]

^https?:\/\/54\.150\.92\.254\/api\/eventTracking\/ - reject

^https?:\/\/[^\/]+\/uploads\/default\/other\/ - reject

^https?:\/\/[^\/]+\/laosiji\/hc237\/uploads\/default\/other\/ - reject

^https?:\/\/www\.google-analytics\.com\/ - reject

^https?:\/\/www\.googletagmanager\.com\/ - reject

[mitm]

hostname = d2x3hbu36ykmr8.cloudfront.net, *.cloudfront.net, d2deyaeqecmerw.cloudfront.net, blpts.az1vu.cn, *.az1vu.cn, huygd.jiekrrj.cn, *.jiekrrj.cn, mmpp4.hcjvdum.com, *.hcjvdum.com, aiimg.syyaann.com, *.syyaann.com, api.usoim.com, *.usoim.com, 54.150.92.254


*******************************/
