/******************************
  
脚本功能：草榴社区——解锁—金币视频—VIP视频
特别说明：开启脚本即可在线观看视频-漫画無解
特别说明：必须开启HTTP抓包,并且关闭其他的脚本
脚本作者：彭于晏💞
更新时间：2026—6-3
TG反馈群：https://t.me/plus8889
TG频道群：https://t.me/py996
使用声明：此脚本仅供学习与交流，请勿转载与贩卖！⚠️⚠️⚠️

*******************************


[rewrite_local]

^https:\/\/[^\/]*\..*\.cn\/\w+\/[a-z0-9]{32}\/[a-z0-9]{32}\.m3u8(\?.*)? url script-request-header https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/clsq.js

^https?:\/\/[^\/]+\/(?:api|pwa)\.php\/api(?:\/api)?\/ url script-response-body https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/clsqad.js

[filter-local]

^https?:\/\/ap\.dc-report\.cc\/ - reject

^https?:\/\/api-dc-prod-002\.cyou\/ - reject

^https?:\/\/api-dc2-prod-02\.cyou\/ - reject

^https?:\/\/[^\/]+\/upload_01\/ads\/ - reject

^https?:\/\/[^\/]+\/upload\/ads\/ - reject

^https?:\/\/[^\/]+\/hc237\/uploads\/ - reject

^https?:\/\/18\.162\.65\.153\/api\/eventTracking\/ - reject

[mitm]

hostname = *.yeuxqifz.cc, *.xoceiqxo.cc, *.ceogberj.cc, *.caanrrim.cc, *.iajckz.cn, *.xmwemv.cn, 120play.*.cn, long.*.cn, *.wpyxbxt.cn, h5play.*.com, *.fipxor.cn, ap.dc-report.cc, api-dc-prod-002.cyou, api-dc2-prod-02.cyou

*******************************/
