/******************************

脚本功能：海角社区——解锁—金币视频—VIP视频
特别说明：开启脚本即可在线观看视频
特别说明：必须开启HTTP抓包,并且关闭其他的脚本
更新时间：2026—5-26
TG反馈群：https://t.me/plus8889
TG频道群：https://t.me/py996
使用声明：此脚本仅供学习与交流，请勿转载与贩卖！⚠️⚠️⚠️

*******************************

[rewrite_local]

^https?:\/\/api2\.[^\/]+\/api\/ url script-response-body https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/hjsq-noad.js
^https:\/\/[^\/]*\..*\.cn\/\w+\/[a-z0-9]{32}\/[a-z0-9]{32}\.m3u8(\?.*)? url script-request-header https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/hdsq.js

[filter-local]

# 广告图 CDN
^https?:\/\/ap\.dc-report\.cc\/ - reject

^https?:\/\/api-dc-prod-002\.cyou\/ - reject

^https?:\/\/api-dc2-prod-02\.cyou\/ - reject

[mitm]

hostname = p4.aozngkwm.com, *.aozngkwm.com, api2.anpbbxdyo.com, *.anpbbxdyo.com, new.iajckz.cn, *.iajckz.cn, *.aavhnube.cc

*******************************/
