[mitm]
hostname = *.cloudfront.net, api-dc-prod-008.cyou, api-dc2-prod-08.cyou, jmnkojis4.com
[filter_local]
HOST-SUFFIX,eqfx9bas.cc,reject
HOST-SUFFIX,yihaici.top,reject
HOST-SUFFIX,epuf3tk.cc,reject
HOST-SUFFIX,va2p.com,reject
URL-REGEX,^https?:\/\/[^/]+\/api\/eventTracking\/batchReport\.json$,reject
[rewrite_local]
^https://[^/]*\.cloudfront\.net/(frontPage|\?|$) url script-request-header https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/jhs.js
^https://[^/]*\.cloudfront\.net/(frontPage|\?|$) url script-response-body https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/jhs.js
^https://[^/]*\.cloudfront\.net\/mp4\/splash- url reject
^https?:\/\/mmmims\.lkkwip\.cn\/ - reject
^https://[^/]*\.cloudfront\.net\/png\/ad-card-bg- url reject
^https://[^/]*\.cloudfront\.net\/png\/buyGold- url reject
^https?:\/\/jmnkojis4\.com\/ url reject-dict
^https?:\/\/[^/]*\.cloudfront\.net\/api\/eventTracking\/batchReport\.json url reject-dict
^https?:\/\/api-dc-prod-008\.cyou\/api\/eventTracking\/batchReport\.json url reject-dict
^https?:\/\/api-dc2-prod-08\.cyou\/api\/eventTracking\/batchReport\.json url reject-dict
^https?:\/\/[^/]*\/api\/app\/ads\/click url reject-dict
^https?:\/\/[^/]*\/api\/app\/recreation\/click url reject-dict
^https?:\/\/[^/]*\/api\/app\/redpacket\/ url reject-dict
