# ==========================================

# 脚本功能：快看漫画——解锁—金币视频—VIP视频-去广告
# 特别说明：开启脚本即可在线观看视频
# 特别说明：必须开启HTTP抓包,并且关闭其他的脚本
# 更新时间：2026—7-11
# TG反馈群：https://t.me/plus8889
# TG频道群：https://t.me/py996
# 使用声明：此脚本仅供学习与交流，请勿转载与贩卖！⚠️⚠️⚠️

# ==========================================

[mitm]
hostname = d3sjt6i1mx4tjc.cloudfront.net, d3k4e7spixznr4.cloudfront.net, api-dc-prod-008.cyou, api-dc2-prod-08.cyou

[filter_local]
URL-REGEX,^https?:\/\/[^/]+\/api\/eventTracking\/batchReport\.json$,reject

[rewrite_local]
# 去广告脚本
^https://d3sjt6i1mx4tjc\.cloudfront\.net/\?.* url script-request-header https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/kkmh.js
^https://d3sjt6i1mx4tjc\.cloudfront\.net/$ url script-request-header https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/kkmh.js
^https://d3sjt6i1mx4tjc\.cloudfront\.net/home-video.* url script-request-header https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/kkmh.js
^https://d3sjt6i1mx4tjc\.cloudfront\.net/acg.* url script-request-header https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/kkmh.js
^https://d3sjt6i1mx4tjc\.cloudfront\.net/mine.* url script-request-header https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/kkmh.js
^https://d3sjt6i1mx4tjc\.cloudfront\.net/\?.* url script-response-body https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/kkmh.js
^https://d3sjt6i1mx4tjc\.cloudfront\.net/$ url script-response-body https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/kkmh.js
^https://d3sjt6i1mx4tjc\.cloudfront\.net/home-video.* url script-response-body https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/kkmh.js
^https://d3sjt6i1mx4tjc\.cloudfront\.net/acg.* url script-response-body https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/kkmh.js
^https://d3sjt6i1mx4tjc\.cloudfront\.net/mine.* url script-response-body https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/kkmh.js

# 事件追踪拦截
^https://d3k4e7spixznr4\.cloudfront\.net/api/eventTracking/batchReport\.json url reject-dict
^https://api-dc-prod-008\.cyou/api/eventTracking/batchReport\.json url reject-dict
^https://api-dc2-prod-08\.cyou/api/eventTracking/batchReport\.json url reject-dict
^https://13\.212\.103\.98/api/eventTracking/batchReport\.json url reject-dict
^https://47\.129\.175\.127/api/eventTracking/batchReport\.json url reject-dict
^https://54\.255\.68\.213/api/eventTracking/batchReport\.json url reject-dict
^https://54\.169\.217\.47/api/eventTracking/batchReport\.json url reject-dict
^https://52\.221\.252\.171/api/eventTracking/batchReport\.json url reject-dict
^https://54\.255\.167\.20/api/eventTracking/batchReport\.json url reject-dict
^https://54\.179\.7\.38/api/eventTracking/batchReport\.json url reject-dict
