/******************************

# 脚本功能：洛丽塔———解锁———金币视频———VIP视频
# 特别说明：必须开启HTTP抓包,并且关闭其他的脚本
# 特别说明：捕获成功后，点击通知即可观看
# 脚本作者：彭于晏💞
# TG反馈群：https://t.me/plus8889
# TG频道群：https://t.me/py996
# 使用声明：此脚本仅供学习与交流，请勿转载与贩卖！⚠️⚠️⚠️

*******************************

[rewrite_local]

^https?:\/\/[^\/]+\/api\/ url script-response-body https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/lltad.js

[filter-local]

^https?:\/\/[^\/]+\/upload_01\/ads\/ - reject
^https?:\/\/[^\/]+\/upload\/ads\/ - reject
^https?:\/\/[^\/]+\/new\/ads\/ - reject
^https?:\/\/[^\/]+\/hc237\/uploads\/ - reject
^https?:\/\/d3k4e7spixznr4\.cloudfront\.net\/ - reject
^https?:\/\/b100\.vaowujej\.com\/ - reject
^https?:\/\/static\.cloudflareinsights\.com\/ - reject
^https?:\/\/16\.163\.146\.202:57892\/ - reject

[mitm]

hostname = p1.ajlqokal.cc, *.ajlqokal.cc, xffer385.com, www.mtyxmcv385.cc, *.mtyxmcv385.cc, api2.fzjrmiga.cc, *.fzjrmiga.cc, new.pfmluq.cn, *.pfmluq.cn, long.ffxddn.cn, 10play.ffxddn.cn, 120play.ffxddn.cn, *.ffxddn.cn, tp2.qzycbu.cn, tp3.qzycbu.cn, tp4.qzycbu.cn, tp5.qzycbu.cn, tp6.qzycbu.cn, tp7.qzycbu.cn, *.qzycbu.cn

*******************************/
