/******************************
  
# 脚本功能：撸先生———解锁———金币视频———VIP视频
# 特别说明：必须开启HTTP抓包,并且关闭其他的脚本
# 特别说明：捕获成功后，点击通知即可观看
# 脚本作者：彭于晏💞
# 更新时间：2026-6-12
# TG反馈群：https://t.me/plus8889
# TG频道群：https://t.me/py996
# 使用声明：此脚本仅供学习与交流，请勿转载与贩卖！⚠️⚠️⚠️

*******************************


[rewrite_local]

^https:\/\/[^\/]*\..*\.cn\/\w+\/[a-z0-9]{32}\/[a-z0-9]{32}\.m3u8(\?.*)? url script-request-header https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/lxs.js

^https?:\/\/[^\/]+\/api\.php url script-response-body https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/lxsad.js


[filter-local]

^https?:\/\/b100\.vaowujej\.com\/ - reject

^https?:\/\/ap\.dc-report\.cc\/ - reject

^https?:\/\/[^\/]+\/hc237\/uploads\/default\/other\/ - reject

^https?:\/\/[^\/]+\/new\/ads\/ - reject

[mitm]

hostname = lusirpwa2.xdfavonw.cc, *.xdfavonw.cc, api.sgzmrybs.cc, *.sgzmrybs.cc, new.cttvvs.cn, tp2.cttvvs.cn, tp3.cttvvs.cn, tp4.cttvvs.cn, tp5.cttvvs.cn, tp6.cttvvs.cn, *.cttvvs.cn, 120play.aibxqo.cn, long.aibxqo.cn, *.aibxqo.cn, b100.vaowujej.com, ap.dc-report.cc, api.hichatapi.info


*******************************/
