/******************************
  
# 脚本功能：奶茶视频——解锁—金币视频—VIP视频-净化广告
# 脚本作者：彭于晏💞
# 更新时间：2026-05-29
# TG反馈群：https://t.me/plus8889
# TG频道群：https://t.me/py996
# 使用声明：此脚本仅供学习与交流，请勿转载与贩卖！⚠️⚠️⚠️

*******************************


[rewrite_local]

^https?:\/\/newapi[a-z]{2}\.[^\/]+\/api\/(user\/read|bootstrap|content\/getNav|points\/info|points\/point_limited\/info|points\/point_limited\/remind|points\/exchange\/config|video\/playNew(?:\/\d+)?|video\/details(?:\/\d+)?) url script-response-body https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/ncsp.js


^https?:\/\/newapisd\.[^\/]+\/api\/ url script-response-body https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/ncspad.js

^https?:\/\/newapicf\.[^\/]+\/ url script-response-body https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/ncspad.js

^https?:\/\/[^\/]+\/uploads\/images\/ads\/ - reject

[filter-local]

^https?:\/\/[^\/]+\/uploads\/images\/ads\/ - reject

[mitm]

hostname = newapisd.bhw6gjej.com, *.bhw6gjej.com, newapicf.sbhq85ek.com, *.sbhq85ek.com, imgwm5zye4k.hzzhxcy.com, *.hzzhxcy.com

*******************************/
