/******************************
  
# 脚本功能：51动漫——解锁—金币视频—VIP视频-去广告-漫画无解
# 特别说明：必须开启HTTP抓包,并且关闭其他的脚本
# 特别说明：捕获成功后，点击通知即可观看
# 脚本作者：彭于晏💞
# 更新时间：2026-6-2
# TG反馈群：https://t.me/plus8889
# TG频道群：https://t.me/py996
# 使用声明：此脚本仅供学习与交流，请勿转载与贩卖！⚠️⚠️⚠️


*******************************


[rewrite_local]

^https:\/\/[^\/]*\..*\.cn\/\w+\/[a-z0-9]{32}\/[a-z0-9]{32}\.m3u8(\?.*)? url script-request-header https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/pilipili.js

^https?:\/\/[^\/]+\/(?:api\.php\/api|api)\/ url script-response-body https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/pilipiliad.js


[filter-local]

^https?:\/\/b100\.vaowujej\.com\/ - reject

^https?:\/\/[^\/]+\/upload_01\/ads\/ - reject

^https?:\/\/[^\/]+\/new\/ads\/ - reject

^https?:\/\/[^\/]+\/hc237\/uploads\/ - reject

[mitm]

hostname = pilipwa4.hmufnno.cc, *.hmufnno.cc, apiv4.kogwzxje.top, *.kogwzxje.top, new.cttvvs.cn, *.cttvvs.cn, tp2.cttvvs.cn, tp3.cttvvs.cn, tp8.cttvvs.cn, 120play.*.cn, long.*.cn, *.aibxqo.cn, h5play.*.com


*******************************/
