#!name=妻社 VIP解锁
#!desc=解锁VIP视频/帖子、去广告弹窗
#!author=Yu9191
#!homepage=https://github.com/Yu9191
#!date=2026-05-13

https://qsh5.qsh526724.com/source/plugin/qsts_app/index.php/config.userInit url script-response-body https://raw.githubusercontent.com/89996462/Quantumult-X/main/ghs/qs.js

hostname = qsh5.qsh526724.com
