/******************************
  
# 脚本功能：哔咔漫画(bkh056)——去广告—会员解锁—付费内容—捕获
# 目标站点：https://zqxz.bkk066.com/line/
# API域名：h5.bkh056.com
# 抓包校验：2026-06-07-204838
# 脚本作者：彭于晏💞
# 更新时间：2026-6-7
# 使用声明：此脚本仅供学习与交流，请勿转载与贩卖！⚠️⚠️⚠️

*******************************

[rewrite_local]

# m3u8/flv 播放链接捕获
^https?:\/\/[^\/]+\/.*\.m3u8(\?.*)?$ url script-request-header https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/bkmh.js
^https?:\/\/[^\/]+\/.*\.flv(\?.*)?$ url script-request-header https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/bkmh.js

# API 响应改包（去广告+解锁）
^https?:\/\/h5\.bkh056\.com\/bkapi\/.* url script-response-body https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/bkmhad.js
[filter_local]

# 广告域名屏蔽
^https?:\/\/fd65ef\.top\/ - reject
^https?:\/\/kg24yb\.top\/ - reject
^https?:\/\/ghtawi\.timemate\.top\/hc\d+\/uploads\/default\/other\/ - reject

# 广告图片屏蔽
^https?:\/\/[^\/]+\/uploads\/default\/other\/.*\.gif(\?.*)?$ - reject

# 统计和追踪屏蔽
^https?:\/\/www\.google-analytics\.com\/ - reject
^https?:\/\/www\.googletagmanager\.com\/ - reject

[mitm]

hostname = zqxz.bkk066.com, h5.bkh056.com, *.bkh056.com, *.bkk066.com, ghtawi.timemate.top, *.timemate.top

*******************************/
